fixed filtering

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -31,46 +31,71 @@ checkDate() {
     if date -d "$1" > /dev/null 2>&1; then
         return 0
     else
+        echo "Invalid date format" >&2
         exit 1
     fi
 }
 
 # filters the list
 filter() {
+    # regex user format
+    userFormat='[[:print:]]+$'
     # regex date format
     dateFormat='^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
-
+    # regex currency format
+    curFormat='^[A-Z]{3}$'
+    # regex number format
+    numFormat='[-]?[0-9]+.[0-9]+$'
+    
     # iterates through files in the file array
     for file in "${files[@]}"; do
         # checks if the file doesn't have .gzip file extension
         if [[ $(file -b "$file") != *"gzip compressed data"* ]]; then
             # if fields are empty it exits with 1 and triggers the error message
             if awk -F ';' '($1 == "" || $2 == "" || $3 == "" || $4 == "") { exit 1 }' "$file"; then
-                # checks if the date is valid using regex and filters the list with arguments input from .log file by the user using awk
-                awk -F ';' -v currency="$currency" -v before="$before" -v after="$after" -v user="$user" -v dateFormat="$dateFormat" '
+                # checks if all the columns in file are valid using regex and filters the list with arguments input from .log file by the user using awk
+                awk -F ';' -v currency="$currency" -v before="$before" -v after="$after" -v user="$user" -v userFormat="$userFormat" -v dateFormat="$dateFormat" -v curFormat="$curFormat" -v numFormat="$numFormat" '
+                    function isValidUser(user) {
+                        return (user ~ userFormat);
+                    }
                     function isValidDate(date) {
                         return (date ~ dateFormat);
                     }
-                    !isValidDate($2) { exit 1 }
+                    function isValidCurrency(cur) {
+                        return (cur ~ curFormat);
+                    }
+                    function isValidNumber(num) {
+                        return (num ~ numFormat);
+                    }
+                    ( !isValidUser($1) || !isValidDate($2) || !isValidCurrency($3) || !isValidNumber($4) ) { exit 1 }
                     ( ($3 == currency || currency == "") && ($1 == user) && ($2 < before || before == "") && ($2 > after || after == "") )
                 ' "$file" || exit 1
             else
-                echo "Error: Fields are empty in $file" >&2
+                echo "Fields are empty in $file" >&2
                 exit 1
             fi
         else
             # if fields are empty it exits with 1 and triggers the error message
             if gzip -dc "$file" | awk -F ';' '($1 == "" || $2 == "" || $3 == "" || $4 == "") { exit 1 }'; then
-                # checks if the date is valid using regex and filters the list with arguments input from .gz file by the user using awk
-                gzip -dc "$file" | awk -F ';' -v currency="$currency" -v before="$before" -v after="$after" -v user="$user" -v dateFormat="$dateFormat" '
+                #  checks if all the columns in file are valid using regex and filters the list with arguments input from .gz file by the user using awk
+                gzip -dc "$file" | awk -F ';' -v currency="$currency" -v before="$before" -v after="$after" -v user="$user" -v userFormat="$userFormat" -v dateFormat="$dateFormat" -v curFormat="$curFormat" -v numFormat="$numFormat" '
+                    function isValidUser(user) {
+                        return (user ~ userFormat);
+                    }
                     function isValidDate(date) {
                         return (date ~ dateFormat);
                     }
-                    !isValidDate($2) { exit 1 }
+                    function isValidCurrency(cur) {
+                        return (cur ~ curFormat);
+                    }
+                    function isValidNumber(num) {
+                        return (num ~ numFormat);
+                    }
+                    ( !isValidUser($1) || !isValidDate($2) || !isValidCurrency($3) || !isValidNumber($4) ) { exit 1 }
                     ( ($3 == currency || currency == "") && ($1 == user) && ($2 < before || before == "") && ($2 > after || after == "") )
                 ' || exit 1
             else
-                echo "Error: Fields are empty in $file" >&2
+                echo "Fields are empty in $file" >&2
                 exit 1
             fi
         fi
@@ -111,7 +136,7 @@ profit() {
 
 # if there are no arguments output error
 if [ $# -eq 0 ]; then
-    echo "Invalid argument: At least one argument is required." >&2
+    echo "Enter at least one argument to run the script!" >&2
     exit 1
 fi
 
@@ -128,6 +153,7 @@ while getopts "a:b:c:" opt; do
     case $opt in
         a)
             if [ -n "$after" ]; then
+                echo "The filter -a cannot be entered more than once!" >&2
                 exit 1
             fi
 
@@ -137,6 +163,7 @@ while getopts "a:b:c:" opt; do
             ;;
         b)
             if [ -n "$before" ]; then
+                echo "The filter -b cannot be entered more than once!" >&2
                 exit 1
             fi
 
@@ -148,6 +175,7 @@ while getopts "a:b:c:" opt; do
             currency="$OPTARG"
             ;;
         *)
+            echo "You have entered an invalid filter! Try again." >&2
             exit 1 
             ;;
     esac
@@ -172,6 +200,7 @@ if [ -n "$1" ] && [ ! -f "$1" ]; then
     user="$1"
     shift
 else
+    echo "Invalid user!" >&2
     exit 1
 fi
 
@@ -206,6 +235,7 @@ case "$com" in
         profit
         ;;
     *)
+        echo "You have entered an invalid command! Try again." >&2
         exit 1
         ;;
 esac
